### ISSUE TITLE
Regression in document.create

### ISSUE THREAD

**Issue by GlennV** [twikey/twikey-api-python#1]
Since the last version, we get the following error when calling `client.document.create(...)`:

```python 
self.logger.debug("Added new mandate : %s" % jsonResponse.mndtId)
    AttributeError: 'dict' object has no attribute 'mndtId'
```

I believe it should be `jsonResponse["mndtId"]` instead.

**Comment by koen-serry** [comment]
Yes, you're right, thanks for giving us a heads-up. Just pushed the fix.
